# Generated by Django 4.1.3 on 2022-11-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='back_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='go_date',
        ),
    ]
