# Generated by Django 4.1.3 on 2022-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_check_in_booking_back_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='back_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='go_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
