# Generated by Django 4.1.3 on 2022-11-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_booking_back_date_alter_booking_go_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
    ]
