# Generated by Django 4.1.3 on 2022-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_alter_booking_back_date_alter_booking_go_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
