# Generated by Django 4.1.3 on 2022-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_booking_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='back_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='go_date',
            field=models.DateTimeField(),
        ),
    ]
